spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root
server:
  port: 8888
mybatis:
  mapper-locations: mapper/*.xml